[package]
name = "stopwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
epi = "0.17.0"
tokio = { version = "1.43.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
